# shearnet/config/default_config.yaml
# Default configuration for ShearNet

# Dataset configuration
dataset:
  samples: 10000
  psf_sigma: 1.0  # PSF sigma
  exp: "ideal"
  seed: 42

# Model configuration  
model:
  type: "mlp"  # Options: simple, enhanced, resnet
  
# Training configuration
training:
  epochs: 10
  batch_size: 32
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  patience: 10
  val_split: 0.2
  eval_interval: 1
  
# Evaluation configuration
evaluation:
  test_samples: 1000
  seed: 58
  
# Output configuration
output:
  save: true  # Whether to save model
  save_path: null  # Will use SHEARNET_DATA_PATH/model_checkpoint if null
  plot_path: null  # Will use SHEARNET_DATA_PATH/plots if null
  model_name: "my_model"
  
# Plotting configuration
plotting:
  plot: true  # Whether to plot learning curves
  save_loss: true  # Whether to save loss arrays
  
# Comparison methods
comparison:
  mcal: false
  ngmix: true
  psf_model: "gauss"
  gal_model: "gauss"