dataset:
  samples: 100000
  psf_sigma: 0.25
  exp: ideal
  nse_sd: 0.001
  seed: 42
model:
  type: research_backed
training:
  epochs: 300
  batch_size: 128
  learning_rate: 0.002
  weight_decay: 0.0001
  patience: 50
  val_split: 0.2
  eval_interval: 1
evaluation:
  test_samples: 5000
  seed: 58
output:
  save_path: /home/adfield/ShearNet_Dev/model_checkpoint
  plot_path: /home/adfield/ShearNet_Dev/plots
  model_name: research_backed_galaxy_resnet_high_noise
plotting:
  plot: true
comparison:
  mcal: true
  ngmix: true
  psf_model: gauss
  gal_model: gauss
