# configs/cnn6_experiment.yaml
dataset:
  samples: 100000
  psf_sigma: 0.25
  exp: "ideal"
  seed: 42

model:
  type: "cnn"
  
training:
  epochs: 300
  batch_size: 128
  patience: 20

evaluation:
  test_samples: 5000
  seed: 58

output:
  model_name: "cnn8"
  
plotting:
  plot: true

# Comparison methods
comparison:
  ngmix: true
  psf_model: "gauss"
  gal_model: "gauss"